[node]
working_dir = "/root/stacks-blockchain/data"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "029266faff4c8e0ca4f934f34996a96af481df94a89b0c9bd515f3536a95682ddc@seed.testnet.hiro.so:30444"
always_use_affirmation_maps = true
require_affirmed_anchor_blocks = true
pox_sync_sample_secs = 30
prometheus_bind = "0.0.0.0:9153"
# If you have an existing node with this value set to true, keep it as true.
stacker = false

[burnchain]
mode = "krypton"
peer_host = "bitcoin"
peer_port = 18444
pox_prepare_length = 100
pox_reward_length = 900

[connection_options]
auth_token = "XXX"
private_neighbors = false

# Add sbtc-signer as an event observer.
# 
# NOTE: See the readme for how to set this value correctly, your endpoint
# may not be named `sbtc-signer:8801`.
#
# It's perfectly fine to have multiple event observers, just add this
# section below your existing one, it'll adds the event observer to the
# events_observers list.
# 
# NOTE: If one of the provided `events_observer` is down, it will stall
# your Stacks node until it gets back-up.
#
# Also, if you _remove_ entries from the `events_observer` section,
# delete the file `event_observers.sqlite` in your chainstate folder
# to prune old events not yet delivered.
[[events_observer]]
endpoint = "sbtc-signer:8801"
events_keys = [
    "SNGWPN3XDAQE673MXYXF81016M50NHF5X5PWWM70.sbtc-registry::print",
]

[[ustx_balance]]
address = "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
amount = 10000000000000000

[[ustx_balance]]
address = "ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF"
amount = 10000000000000000

[[ustx_balance]]
address = "ST221Z6TDTC5E0BYR2V624Q2ST6R0Q71T78WTAX6H"
amount = 10000000000000000

[[ustx_balance]]
address = "ST2TFVBMRPS5SSNP98DQKQ5JNB2B6NZM91C4K3P7B"
amount = 10000000000000000

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 1

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 2

[[burnchain.epochs]]
epoch_name = "2.2"
start_height = 3

[[burnchain.epochs]]
epoch_name = "2.3"
start_height = 4

[[burnchain.epochs]]
epoch_name = "2.4"
start_height = 5

[[burnchain.epochs]]
epoch_name = "2.5"
start_height = 6

[[burnchain.epochs]]
epoch_name = "3.0"
start_height = 56_457

[[burnchain.epochs]]
epoch_name = "3.1"
start_height = 77_770
