
# Set to your project's Clarinet config file
clarinet = "./Clarinet.toml"

# Set where you'd like TypeScript types output.
# Comment or remove section to skip TypeScript types
[types]
# `output` should be a path to a single file
output = "tests/clarigen-types.ts"

# You can also specify multiple output paths:
# outputs = [
#   "src/clarigen-types.ts",
#   "test/clarigen-types.ts"
# ]

after = "pnpm prettier --log-level error -w ./tests/clarigen-types.ts"

# Set where you'd like generated contract docs
# Generate docs by running `clarigen docs`
[docs]
# `output` should be a folder
output = "docs"

# `docs.after` - script to run after docs are generated.
after = "pnpm prettier --log-level error -w ./docs"
